Traceback (most recent call last):
  File "streams.py", line 3, in <module>
    raise ValueError("This is an error")
ValueError: This is an error
